#! /bin/bash

rm -f config.mk
touch config.mk

MACHINE=$(uname -m 2>/dev/null)

case $MACHINE in
  i386 | i686 | i86pc)
    CACHE_LINE=32
  ;;
  amd64 | x86_64)
    CACHE_LINE=64
  ;;
  *)
    CACHE_LINE=32
  ;;
esac

echo "CACHE_LINE=$CACHE_LINE" >> config.mk

